name: 'Openzim Docker Action'
description: 'Build and publish Docker Images'
inputs:
  image-path:
    description: target image path on both registries (ex. 'openzim/dnscache')
    required: true
  context:
    description: folder to use as context for the build (ex. '.' or 'dnscache')
    required: false
    default: '.'
  on-master:
    description: tag to use on master commits. (ex. 'latest' or 'dev') Leave out if not wanted
    required: false
  tag-pattern:
    description: pattern to trigger image tagging (ex. 'dnscache-v*')
    required: false
  latest-on-tag:
    description: should matched tag be tagged as 'latest' also? (true or false)
    required: false
    default: false
  restrict-to:
    description: repository path to limit this action to (ex. 'openzim/zimfarm')
    required: false
runs:
  using: "composite"
  steps:
    - name: set empty IMAGE_TAGS
      run: echo "IMAGE_TAGS=" >> $GITHUB_ENV
      shell: bash

    - name: Compute image tags
      run: python3 $GITHUB_ACTION_PATH/compute_tags.py
      shell: bash
      env:
        IMAGE_PATH: ${{ inputs.image-path }}
        CONTEXT: ${{ inputs.context }}
        ON_MASTER: ${{ inputs.on-master }}
        TAG_PATTERN: ${{ inputs.tag-pattern }}
        LATEST_ON_TAG: ${{ inputs.latest-on-tag }}
        RESTRICT_TO: ${{ inputs.restrict-to }}
        TAGS: ${{ inputs.tags }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

    - name: Verify image tags
      run: echo IMAGE_TAGS $IMAGE_TAGS
      shell: bash

    - name: Checkout Code
      if: inputs.context == '.'
      uses: actions/checkout@v2.3.4

    - name: Checkout Code
      if: inputs.context != '.'
      uses: actions/checkout@v2.3.4
      with:
        path: __repository

    - name: move context
      if: inputs.context != '.'
      run: |
        mv __repository/${{ inputs.context }}/* .
        rm -rf __repository
      shell: bash

    - name: Setup BuildX
      if: $IMAGE_TAGS != ''
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      if: $IMAGE_TAGS != ''
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Login to GitHub Container Registry
      if: $IMAGE_TAGS != ''
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      if: $IMAGE_TAGS != ''
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        tags: $IMAGE_TAGS
